version: "3.8"

services:
  backend:
    build: .
    container_name: youtube_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
